---
# Defines tasks to install and configure Postfix

- name: Include the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages for Debian derivatives
  apt:
    pkg: "{{ item }}"
    state: "{{ packages_state }}"
    update_cache: yes
    cache_valid_time: 14400
  with_items: postfix_packages

- name: ensure that service is enabled
  service: name={{ postfix_service }} enabled=yes

- name: Write Postfix header_checks template
  template:
    src: etc/postfix/header_checks.j2
    dest: "{{ postfix_config_dir }}/header_checks"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart postfix
  when: postfix_header_checks


- name: Write Postfix configuration template
  template:
    src: etc/postfix/main.cf.j2
    dest: "{{ postfix_config_dir }}/main.cf"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart postfix